config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :pages
  resources :enrolments
  resources :courses
  resources :organizations, shallow: true do
    resources :users
    resources :lessons
    resources :aircrafts
    resources :flights
  end

  resources :entries  do
    resource :user, only: [:show, :edit, :update, :destroy]
    resource :lesson, only: [:show, :edit, :update, :destroy]
    resource :aircraft, only: [:show, :edit, :update, :destroy]
    resource :flight, only: [:show, :edit, :update, :destroy]
  end

  resources :lessons, shallow: true do
    resources :entries
  end
  resources :endorsements, shallow: true do
    resources :lessons
  end
  resources :ratings, shallow: true do
    resources :lessons
  end

  resources :aircrafts, shallow: true do
    resources :endorsements
    resources :ratings
    resources :flights
  end
  resources :flights do
    resource :aircraft, only: [:show, :edit, :update, :destroy]
    resources :users
    resources :entries
  end
  resources :users, shallow: true do
    resources :entries
    resources :endorsements
    resources :ratings
    resources :flights
  end

  get '/', to: 'flights#index'

end

app/models/aircraft.rb
class Aircraft < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/endorsement.rb
class Endorsement < ApplicationRecord
end

app/models/enrolment.rb
class Enrolment < ApplicationRecord
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/flight.rb
class Flight < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
end

app/models/organization.rb
class Organization < ApplicationRecord
  validates :name, :slug, presense: true, uniqueness: true
  validates :domain, uniqueness: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/enrolments_controller.rb
class EnrolmentsController < ApplicationController
  before_action :set_enrolment, only: [:show, :edit, :update, :destroy]

  # GET /enrolments
  def index
    @enrolments = Enrolment.all
  end

  # GET /enrolments/1
  def show
  end

  # GET /enrolments/new
  def new
    @enrolment = Enrolment.new
  end

  # GET /enrolments/1/edit
  def edit
  end

  # POST /enrolments
  def create
    @enrolment = Enrolment.new(enrolment_params)

    if @enrolment.save
      redirect_to @enrolment, notice: 'Enrolment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /enrolments/1
  def update
    if @enrolment.update(enrolment_params)
      redirect_to @enrolment, notice: 'Enrolment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /enrolments/1
  def destroy
    @enrolment.destroy
    redirect_to enrolments_url, notice: 'Enrolment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrolment
      @enrolment = Enrolment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def enrolment_params
      params.fetch(:enrolment, {})
    end
end

app/helpers/aircrafts_helper.rb
module AircraftsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def uikit_alert flash_type
    case flash_type
      when 'success'
        'uk-alert-success'
      when 'error'
        'uk-alert-danger'
      when 'alert'
        'uk-alert-warning'
      when 'notice'
        'uk-alert-primary'
      else
        'uk-alert-primary'
    end
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrolments_helper.rb
module EnrolmentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/enrolments/_form.html.haml
= form_for @enrolment do |f|
  - if @enrolment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@enrolment.errors.count, "error")} prohibited this enrolment from being saved:"
      %ul
        - @enrolment.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/enrolments/edit.html.haml
%h1 Editing enrolment

= render 'form'

= link_to 'Show', @enrolment
\|
= link_to 'Back', enrolments_path

app/views/enrolments/index.html.haml
%h1 Listing enrolments

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @enrolments.each do |enrolment|
      %tr
        %td= link_to 'Show', enrolment
        %td= link_to 'Edit', edit_enrolment_path(enrolment)
        %td= link_to 'Destroy', enrolment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Enrolment', new_enrolment_path

app/views/enrolments/new.html.haml
%h1 New enrolment

= render 'form'

= link_to 'Back', enrolments_path

app/views/enrolments/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_enrolment_path(@enrolment)
\|
= link_to 'Back', enrolments_path