config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :pages
  resources :enrolments
  resources :courses
  resources :organizations, shallow: true do
    resources :users
    resources :lessons
    resources :aircrafts
    resources :flights
  end

  resources :entries  do
    resource :user, only: [:show, :edit, :update, :destroy]
    resource :lesson, only: [:show, :edit, :update, :destroy]
    resource :aircraft, only: [:show, :edit, :update, :destroy]
    resource :flight, only: [:show, :edit, :update, :destroy]
  end

  resources :lessons, shallow: true do
    resources :entries
  end
  resources :endorsements, shallow: true do
    resources :lessons
  end
  resources :ratings, shallow: true do
    resources :lessons
  end

  resources :aircrafts, shallow: true do
    resources :endorsements
    resources :ratings
    resources :flights
  end
  resources :flights do
    resource :aircraft, only: [:show, :edit, :update, :destroy]
    resources :users
    resources :entries
  end
  resources :users, shallow: true do
    resources :entries
    resources :endorsements
    resources :ratings
    resources :flights
  end

  get '/', to: 'flights#index'

end

app/models/aircraft.rb
class Aircraft < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/endorsement.rb
class Endorsement < ApplicationRecord
end

app/models/enrolment.rb
class Enrolment < ApplicationRecord
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/flight.rb
class Flight < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
end

app/models/organization.rb
class Organization < ApplicationRecord
  validates :name, :slug, presense: true, uniqueness: true
  validates :domain, uniqueness: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/aircrafts_controller.rb
class AircraftsController < ApplicationController
  before_action :set_aircraft, only: [:show, :edit, :update, :destroy]

  # GET /aircrafts
  def index
    @aircrafts = Aircraft.all
  end

  # GET /aircrafts/1
  def show
  end

  # GET /aircrafts/new
  def new
    @aircraft = Aircraft.new
  end

  # GET /aircrafts/1/edit
  def edit
  end

  # POST /aircrafts
  def create
    @aircraft = Aircraft.new(aircraft_params)

    if @aircraft.save
      redirect_to @aircraft, notice: 'Aircraft was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /aircrafts/1
  def update
    if @aircraft.update(aircraft_params)
      redirect_to @aircraft, notice: 'Aircraft was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /aircrafts/1
  def destroy
    @aircraft.destroy
    redirect_to aircrafts_url, notice: 'Aircraft was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aircraft
      @aircraft = Aircraft.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def aircraft_params
      params.fetch(:aircraft, {})
    end
end

app/helpers/aircrafts_helper.rb
module AircraftsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def uikit_alert flash_type
    case flash_type
      when 'success'
        'uk-alert-success'
      when 'error'
        'uk-alert-danger'
      when 'alert'
        'uk-alert-warning'
      when 'notice'
        'uk-alert-primary'
      else
        'uk-alert-primary'
    end
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrolments_helper.rb
module EnrolmentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/aircrafts/_form.html.haml
= form_for @aircraft do |f|
  - if @aircraft.errors.any?
    #error_explanation
      %h2= "#{pluralize(@aircraft.errors.count, "error")} prohibited this aircraft from being saved:"
      %ul
        - @aircraft.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/aircrafts/edit.html.haml
%h1 Editing aircraft

= render 'form'

= link_to 'Show', @aircraft
\|
= link_to 'Back', aircrafts_path

app/views/aircrafts/index.html.haml
%h1 Listing aircrafts

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @aircrafts.each do |aircraft|
      %tr
        %td= link_to 'Show', aircraft
        %td= link_to 'Edit', edit_aircraft_path(aircraft)
        %td= link_to 'Destroy', aircraft, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Aircraft', new_aircraft_path

app/views/aircrafts/new.html.haml
%h1 New aircraft

= render 'form'

= link_to 'Back', aircrafts_path

app/views/aircrafts/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_aircraft_path(@aircraft)
\|
= link_to 'Back', aircrafts_path