config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :pages
  resources :enrolments
  resources :courses
  resources :organizations, shallow: true do
    resources :users
    resources :lessons
    resources :aircrafts
    resources :flights
  end

  resources :entries  do
    resource :user, only: [:show, :edit, :update, :destroy]
    resource :lesson, only: [:show, :edit, :update, :destroy]
    resource :aircraft, only: [:show, :edit, :update, :destroy]
    resource :flight, only: [:show, :edit, :update, :destroy]
  end

  resources :lessons, shallow: true do
    resources :entries
  end
  resources :endorsements, shallow: true do
    resources :lessons
  end
  resources :ratings, shallow: true do
    resources :lessons
  end

  resources :aircrafts, shallow: true do
    resources :endorsements
    resources :ratings
    resources :flights
  end
  resources :flights do
    resource :aircraft, only: [:show, :edit, :update, :destroy]
    resources :users
    resources :entries
  end
  resources :users, shallow: true do
    resources :entries
    resources :endorsements
    resources :ratings
    resources :flights
  end

  get '/', to: 'flights#index'

end

app/models/aircraft.rb
class Aircraft < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/endorsement.rb
class Endorsement < ApplicationRecord
end

app/models/enrolment.rb
class Enrolment < ApplicationRecord
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/flight.rb
class Flight < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
end

app/models/organization.rb
class Organization < ApplicationRecord
  validates :name, :slug, presense: true, uniqueness: true
  validates :domain, uniqueness: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  before_action :set_endorsement, only: [:show, :edit, :update, :destroy]

  # GET /endorsements
  def index
    @endorsements = Endorsement.all
  end

  # GET /endorsements/1
  def show
  end

  # GET /endorsements/new
  def new
    @endorsement = Endorsement.new
  end

  # GET /endorsements/1/edit
  def edit
  end

  # POST /endorsements
  def create
    @endorsement = Endorsement.new(endorsement_params)

    if @endorsement.save
      redirect_to @endorsement, notice: 'Endorsement was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /endorsements/1
  def update
    if @endorsement.update(endorsement_params)
      redirect_to @endorsement, notice: 'Endorsement was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /endorsements/1
  def destroy
    @endorsement.destroy
    redirect_to endorsements_url, notice: 'Endorsement was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endorsement
      @endorsement = Endorsement.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def endorsement_params
      params.fetch(:endorsement, {})
    end
end

app/helpers/aircrafts_helper.rb
module AircraftsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/enrolments_helper.rb
module EnrolmentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/endorsements/_form.html.haml
= form_for @endorsement do |f|
  - if @endorsement.errors.any?
    #error_explanation
      %h2= "#{pluralize(@endorsement.errors.count, "error")} prohibited this endorsement from being saved:"
      %ul
        - @endorsement.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/endorsements/edit.html.haml
%h1 Editing endorsement

= render 'form'

= link_to 'Show', @endorsement
\|
= link_to 'Back', endorsements_path

app/views/endorsements/index.html.haml
%h1 Listing endorsements

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @endorsements.each do |endorsement|
      %tr
        %td= link_to 'Show', endorsement
        %td= link_to 'Edit', edit_endorsement_path(endorsement)
        %td= link_to 'Destroy', endorsement, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Endorsement', new_endorsement_path

app/views/endorsements/new.html.haml
%h1 New endorsement

= render 'form'

= link_to 'Back', endorsements_path

app/views/endorsements/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_endorsement_path(@endorsement)
\|
= link_to 'Back', endorsements_path