config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :pages
  resources :enrolments
  resources :courses
  resources :organizations, shallow: true do
    resources :users
    resources :lessons
    resources :aircrafts
    resources :flights
  end

  resources :entries  do
    resource :user, only: [:show, :edit, :update, :destroy]
    resource :lesson, only: [:show, :edit, :update, :destroy]
    resource :aircraft, only: [:show, :edit, :update, :destroy]
    resource :flight, only: [:show, :edit, :update, :destroy]
  end

  resources :lessons, shallow: true do
    resources :entries
  end
  resources :endorsements, shallow: true do
    resources :lessons
  end
  resources :ratings, shallow: true do
    resources :lessons
  end

  resources :aircrafts, shallow: true do
    resources :endorsements
    resources :ratings
    resources :flights
  end
  resources :flights do
    resource :aircraft, only: [:show, :edit, :update, :destroy]
    resources :users
    resources :entries
  end
  resources :users, shallow: true do
    resources :entries
    resources :endorsements
    resources :ratings
    resources :flights
  end

  get '/', to: 'flights#index'

end

app/models/aircraft.rb
class Aircraft < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/endorsement.rb
class Endorsement < ApplicationRecord
end

app/models/enrolment.rb
class Enrolment < ApplicationRecord
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/flight.rb
class Flight < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
end

app/models/organization.rb
class Organization < ApplicationRecord
  validates :name, :slug, presense: true, uniqueness: true
  validates :domain, uniqueness: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/rating.rb
class Rating < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  def create
    @organization = Organization.new(organization_params)

    if @organization.save
      redirect_to @organization, notice: 'Organization was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /organizations/1
  def update
    if @organization.update(organization_params)
      redirect_to @organization, notice: 'Organization was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /organizations/1
  def destroy
    @organization.destroy
    redirect_to organizations_url, notice: 'Organization was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def organization_params
      params.fetch(:organization, {})
    end
end

app/helpers/aircrafts_helper.rb
module AircraftsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrolments_helper.rb
module EnrolmentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/organizations/_form.html.haml
= form_for @organization do |f|
  - if @organization.errors.any?
    #error_explanation
      %h2= "#{pluralize(@organization.errors.count, "error")} prohibited this organization from being saved:"
      %ul
        - @organization.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/organizations/edit.html.haml
%h1 Editing organization

= render 'form'

= link_to 'Show', @organization
\|
= link_to 'Back', organizations_path

app/views/organizations/index.html.haml
%h1 Listing organizations

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @organizations.each do |organization|
      %tr
        %td= link_to 'Show', organization
        %td= link_to 'Edit', edit_organization_path(organization)
        %td= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Organization', new_organization_path

app/views/organizations/new.html.haml
%h1 New organization

= render 'form'

= link_to 'Back', organizations_path

app/views/organizations/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_organization_path(@organization)
\|
= link_to 'Back', organizations_path